android {
    compileSdk = libraryCompileSdkVersion
    defaultConfig {
        minSdk = libraryMinimumSdkVersion
        targetSdk = libraryTargetSdkVersion
    }
    lint.abortOnError = false
    kotlin{
        jvmToolchain(21)
    }
    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}